@startuml
'https://plantuml.com/use-case-diagram

(回测项目) --> (策略实现)
(策略实现) --> (下单接口)
(策略实现) --> (平仓接口)
(策略实现) --> (初始化信息接口)
(初始化信息接口) --> (交易日期段)
(初始化信息接口) --> (账户金额)

(回测项目) --> (结果展示)
(结果展示) --> (调仓记录)
(结果展示) --> (持仓记录)
(结果展示) --> (收益情况)
@enduml